services:
    spark-master:
        container_name: spark-master
        image: docker.io/bitnami/spark:latest
        networks:
            - hw10-network
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - "8080:8080"
            - "7077:7077"
        volumes:
            - ./app:/opt/app
            - ./data.csv:/opt/app/data.csv

    spark-worker:
        container_name: spark-worker
        image: docker.io/bitnami/spark:latest
        networks:
            - hw10-network
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./app:/opt/app
            - ./data.csv:/opt/app/data.csv



networks:
    hw10-network:
        name: hw10-network
